# .github/workflows/pr-push.yml
name: Echidna Auto-publish
on:
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Begin spec-prod...
        uses: actions/checkout@v4
      - name: Setup Node 22...
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install did-extensions tooling...
        working-directory: tooling
        run: npm i
      - name: Validate did-extensions DID method entries
        working-directory: tooling
        run: npm run validate
      - name: Generate did-extensions registry index
        working-directory: tooling
        run: npm run generate
      - uses: w3c/spec-prod@v2
        with:
          #W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN }}
          W3C_WG_DECISION_URL: https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-06-09-did#resolution1
          W3C_BUILD_OVERRIDE: |
             shortName: did-extensions
             specStatus: NOTE
